Login modifications on tracker to work with training application
iupui-soic/dhis2-android-trackercapture pull request #1
Opened 2018-02-01 01:21 UTC by Ezmeyers

Here are the changes to tracker-capture to allow automatic login with training application, will create a pull request for training app shortly. thanks!

2018-02-01 20:35 UTC, sunbiz requested changes
I don't think we should ~~include~~ modify the gradlew, gradle-wrapper.jar, gradle-wrapper.properties and other files. ~~Can you please remove those files from the commit, or add them to .gitignore, so that they don't get committed again.~~

2018-02-01 22:43 UTC, Ezmeyers commented
The tracker-capture hosted by DHIS2 has these included, do you still want me to remove? If so, no problem

2018-02-03 10:30 UTC, sunbiz requested changes

2018-02-03 10:30 UTC, sunbiz commented on app/src/main/AndroidManifest.xml
> +        <receiver
Only this change is required. All the other changes are not appropriate

2018-02-03 10:30 UTC, sunbiz commented on app/src/main/java/org/hisp/dhis/android/trackercapture/MainActivity.java
>  import android.content.Intent;
No change is required to MainActivity.java

2018-02-03 10:30 UTC, sunbiz commented on app/gradlew
> +#!/usr/bin/env bash
No changes required to app/gradlew

2018-02-03 10:30 UTC, sunbiz commented on app/gradle/wrapper/gradle-wrapper.properties
> +#Thu Nov 30 01:08:05 EST 2017
No changes required to app/gradle/wrapper/gradle-wrapper.properties

2018-02-03 10:30 UTC, sunbiz commented on app/gradlew.bat
> +@if "%DEBUG%" == "" @echo off
No changes are required to app/gradlew.bat

2018-02-03 10:30 UTC, sunbiz commented on app/proguard-rules.pro
>  #-keepclassmembers class fqcn.of.javascript.interface.for.webview {
No changes required to app/proguard-rules.pro

2018-02-03 19:13 UTC, closed without merging